### ISSUE TITLE
Agular 시장 점유율

### ISSUE THREAD

**Issue by justinjoy** [opensource-skt/guide#1]
> 개발자들은 Angular를 많은 확장 프로그램과 도구의 개발에 개발하는 데 사용되었고, 구글은 이러한 도구를 다시 사용하면서 Angular를 오픈소스로 공개한 이득을 충분히 취하였습니다. 

위 내용을 읽으면서 결정권자 입장에서 어떠한 생각을 할까에 대해서 질문을 던져봤습니다.
취한 이득의 규모를 명확히 밝혀서 오픈 소스 광신자(Open source enthusiast)로 평가 절하되는 상황을 막아보았으면 합니다. 

대부분의 오픈소스 프로젝트를 시장 규모로 환산을 하는 것은 매우 어렵겠지만, 
전체 시장에서 미치는 영향력을 간접적으로 정리한 글[1]이 있어서 첨부드립니다.

> Angluar가 구글에 가져다 직접적인 매출을 산정하는 것은 불가능 하지만, 간접 지표를 활용해 볼때, 링크드인의 Job Tag 분석에 따르면 약 70만개 이상의 일자리를 창출하고 있고, 실제 Angluar를 이용한 상품 시장은 고용 시장 보다 클 것으로 예상된다.

일단 워딩 자체는 생각나는 대로 써서 다듬어야할 것 같습니다만, 위와 같은 맺으면 어떨까하고 의견을 드립니다.

[1] https://www.codeinwp.com/blog/angular-vs-vue-vs-react/

**Comment by haksungjang** [comment]
의견 감사합니다!
다음과 같이 반영 하였습니다. 혹시, 추가 의견 있다면 알려주세요~
"개발자들은 Angular를 사용하여 많은 확장 프로그램과 도구를 개발하고, 구글은 다시 러한 확장 프로그램과 도구를 활용하는 이득을 취할 수 있었습니다. Angluar가 구글에 가져다 준 직접적인 매출을 산정하는 것은 쉽지 않겠지만, 링크드인의 Job Tag 분석(https://www.codeinwp.com/blog/angular-vs-vue-vs-react/)에 따르면 약 70만개 이상의 일자리가 창출되었는데, 이러한 고용 시장을 고려할 때 Angluar를 이용한 상품 시장 역시 상당히 클 것으로 예상할 수 있습니다."
