### ISSUE TITLE
Open source license metrics

### ISSUE THREAD

**Issue by justinjoy** [opensource-skt/guide#2]
다양한 오픈 소스 라이센스를 모두 파악하고 있는 것은 어려운일이라, 특성에 따라 분류를 해서 적절한 라이센스를 사용할수 있도록 가이드를 추가하면 어떨까 싶습니다.

다행이도 예전에 수령했던 가이드가 있어 초안을 첨부드립니다.

  - 외부에 소스코드를 공개하는 경우에 활용과 보급 또는 저변 확대를 통한 사업 경쟁력 강화가 목적인 경우에는 허용 라이선스(permissive license)를 적용할 수 있다.
    - Apache License
    - BSD
  - 외부 개발자의 집단 지성을 통해 소프트웨어의 품질을 제고하려는 목적인 경우에는 반환 라이선스(reciprocal license)를 적용할 수 있다
    - GPL류
 - 회사의 영업 비밀 또는 특허에 해당하는 핵심 모듈은 오픈소스 형태로 외부 공개하지 않는다

**Comment by haksungjang** [comment]
의견 감사합니다! 
가이드 작성 시 참고하겠습니다. ^^
